import {
  Award,
  BadgeCheck,
  Box,
  Briefcase,
  Calendar,
  CheckCircle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  Droplets,
  Eye,
  Factory,
  FileSearch,
  FileText,
  Flame,
  FlaskConical,
  Globe,
  GraduationCap,
  HardHat,
  Layers,
  Microscope,
  PenTool,
  Ruler,
  Search,
  Settings2,
  ShieldCheck,
  Star,
  Timer,
  Train,
  TrendingUp,
  UserCheck,
  Users,
  Warehouse,
  Wrench,
  Zap,
  type LucideProps,
} from 'lucide-react'

type IconComponent = React.ComponentType<LucideProps>

export const ICON_REGISTRY: Record<string, IconComponent> = {
  Award,
  BadgeCheck,
  Box,
  Briefcase,
  Calendar,
  CheckCircle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  Droplets,
  Eye,
  Factory,
  FileSearch,
  FileText,
  Flame,
  FlaskConical,
  Globe,
  GraduationCap,
  HardHat,
  Layers,
  Microscope,
  PenTool,
  Ruler,
  Search,
  Settings2,
  ShieldCheck,
  Star,
  Timer,
  Train,
  TrendingUp,
  UserCheck,
  Users,
  Warehouse,
  Wrench,
  Zap,
}

const NUMBER_FALLBACK: Record<string, IconComponent> = {
  '18+':      Clock,
  '10+':      ClipboardList,
  '5+':       TrendingUp,
  '550+':     Warehouse,
  '500+':     Users,
  '111':      Zap,
  '131':      Zap,
  '135':      Zap,
  '136/138':  Zap,
  '141':      Flame,
  'IWE':      GraduationCap,
  'IWI':      Search,
  'VT2':      Eye,
  'PT2':      Droplets,
  'WPS':      FileText,
  'WPQR':     ClipboardCheck,
  'ISO 3834': ShieldCheck,
  'EN 1090':  Layers,
  'EN 15085': Train,
  'ISO 9606': UserCheck,
  'ISO 14732':Settings2,
  'ISO 14731':Briefcase,
  'B1':       Globe,
  'B+R':      FlaskConical,
  '2D':       PenTool,
  '3D':       Box,
}

export function getTileIcon(number: string, iconName?: string | null): IconComponent {
  if (iconName) return ICON_REGISTRY[iconName] ?? FileSearch
  return NUMBER_FALLBACK[number] ?? FileSearch
}
