import type { CollectionConfig } from 'payload'

export const StatTile: CollectionConfig = {
  slug: 'stat-tiles',
  labels: {
    singular: 'Kafelek',
    plural: 'Kafelki statystyk',
  },
  access: {
    read: () => true,
  },
  defaultSort: 'order',
  fields: [
    {
      name: 'number',
      label: 'Liczba / wartość (np. 18+, IWE)',
      type: 'text',
      required: true,
    },
    {
      name: 'label',
      label: 'Etykieta (np. Lat doświadczenia)',
      type: 'text',
      required: true,
    },
    {
      name: 'icon',
      label: 'Ikona',
      type: 'select',
      options: [
        { label: 'Zegar (Clock)',                    value: 'Clock' },
        { label: 'Timer (Timer)',                    value: 'Timer' },
        { label: 'Trend wzrostowy (TrendingUp)',     value: 'TrendingUp' },
        { label: 'Magazyn (Warehouse)',              value: 'Warehouse' },
        { label: 'Użytkownicy (Users)',              value: 'Users' },
        { label: 'Błyskawica - spawanie (Zap)',      value: 'Zap' },
        { label: 'Płomień - TIG (Flame)',            value: 'Flame' },
        { label: 'Dyplom (GraduationCap)',           value: 'GraduationCap' },
        { label: 'Lupa / inspekcja (Search)',        value: 'Search' },
        { label: 'Oko - VT (Eye)',                   value: 'Eye' },
        { label: 'Krople - PT (Droplets)',           value: 'Droplets' },
        { label: 'Dokument (FileText)',              value: 'FileText' },
        { label: 'Clipboard z check (ClipboardCheck)', value: 'ClipboardCheck' },
        { label: 'Clipboard z listą (ClipboardList)', value: 'ClipboardList' },
        { label: 'Tarcza z check (ShieldCheck)',     value: 'ShieldCheck' },
        { label: 'Warstwy - EN 1090 (Layers)',       value: 'Layers' },
        { label: 'Pociąg - EN 15085 (Train)',        value: 'Train' },
        { label: 'Użytkownik z check (UserCheck)',   value: 'UserCheck' },
        { label: 'Ustawienia (Settings2)',           value: 'Settings2' },
        { label: 'Teczka (Briefcase)',               value: 'Briefcase' },
        { label: 'Globus - języki (Globe)',          value: 'Globe' },
        { label: 'Kolba - B+R (FlaskConical)',       value: 'FlaskConical' },
        { label: 'Pióro - 2D (PenTool)',             value: 'PenTool' },
        { label: 'Sześcian - 3D (Box)',              value: 'Box' },
        { label: 'Nagroda (Award)',                  value: 'Award' },
        { label: 'Odznaka (BadgeCheck)',             value: 'BadgeCheck' },
        { label: 'Kask (HardHat)',                   value: 'HardHat' },
        { label: 'Klucz / narzędzie (Wrench)',       value: 'Wrench' },
        { label: 'Fabryka (Factory)',                value: 'Factory' },
        { label: 'Linijka (Ruler)',                  value: 'Ruler' },
        { label: 'Mikroskop (Microscope)',           value: 'Microscope' },
        { label: 'Procesor (Cpu)',                   value: 'Cpu' },
        { label: 'Okrąg z check (CheckCircle)',      value: 'CheckCircle' },
        { label: 'Gwiazdka (Star)',                  value: 'Star' },
        { label: 'Kalendarz (Calendar)',             value: 'Calendar' },
      ],
      admin: {
        description: 'Ikona wyświetlana przy kafelku na stronie i w popupie',
        components: {
          Field: '@/components/admin/IconPickerField',
        },
      },
    },
    {
      name: 'description',
      label: 'Opis szczegółowy (widoczny w popupie)',
      type: 'textarea',
      required: true,
    },
    {
      name: 'order',
      label: 'Kolejność wyświetlania',
      type: 'number',
      defaultValue: 0,
      admin: {
        description: 'Mniejsza liczba = wyświetla się wcześniej',
      },
    },
  ],
}
